[tool.portray]
output_dir = "docs"
extra_dirs = ["PyLinuxDiagnosticToolKit/sshConnector", "PyLinuxDiagnosticToolKit/LinuxModules", "PyLinuxDiagnosticToolKit/libs"]
modules = ["PyLinuxDiagnosticToolKit/sshConnector/sshLibs/SCPChannel",
    "PyLinuxDiagnosticToolKit/sshConnector/sshLibs/SFTPChannel",
    "PyLinuxDiagnosticToolKit/sshConnector/sshConnect",
    "PyLinuxDiagnosticToolKit/sshConnector/sshBufferControl",
    "PyLinuxDiagnosticToolKit/sshConnector/sshEnvironmentControl",
    "PyLinuxDiagnosticToolKit/sshConnector/sshEnvironmentManager",
    "PyLinuxDiagnosticToolKit/sshConnector/sshThreader",
    "PyLinuxDiagnosticToolKit/sshConnector/sshLibs/sshChannelEnvironment",
    "PyLinuxDiagnosticToolKit/LinuxModules/genericCmdModule",
    "PyLinuxDiagnosticToolKit/LinuxModules/CommandContainers",
    "PyLinuxDiagnosticToolKit/ldtk"]


[[tool.portray.mkdocs.nav]]
Summary = "README.md"

[[tool.portray.mkdocs.nav]]
Tutorial = "TUTORIAL.md"

[[tool.portray.mkdocs.nav]]
sshConnector = "PyLinuxDiagnosticToolKit/sshConnector/README.md"

[[tool.portray.mkdocs.nav]]
CommandContainer = "PyLinuxDiagnosticToolKit/LinuxModules/README.md"
